<!DOCTYPE html>
<?php
if (config::enable_offline_mode) {
	echo '<html manifest="offline.manifest.php">';
}
else {
	echo '<html>';
}
?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Visio Online</title>

<!-- Libraries -->
<script type="text/javascript" src="js/lib/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="js/lib/raphael-min.js"></script>

<!-- JavaScript -->
<script type="text/javascript" src="js/vonline.js"></script>
<script type="text/javascript" src="js/functions.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>

<script type="text/javascript" src="js/dialog.js"></script>

<script type="text/javascript" src="js/document.js"></script>

<script type="text/javascript" src="js/sidebar.js"></script>

<script type="text/javascript" src="js/menu.js"></script>
<script type="text/javascript" src="js/menuitem.js"></script>

<script type="text/javascript" src="js/category.js"></script>
<script type="text/javascript" src="js/categoryitem.js"></script>
<script type="text/javascript" src="js/categoryeditview.js"></script>

<script type="text/javascript" src="js/snapshothistory.js"></script>

<script type="text/javascript" src="js/canvas.js"></script>
<script type="text/javascript" src="js/selection.js"></script>

<script type="text/javascript" src="js/base.js"></script>
<script type="text/javascript" src="js/rectangle.js"></script>
<script type="text/javascript" src="js/connection.js"></script>
<script type="text/javascript" src="js/annotation.js"></script>
<script type="text/javascript" src="js/path.js"></script>

<script type="text/javascript" src="js/commands/translate.js"></script>
<script type="text/javascript" src="js/commands/scale.js"></script>
<script type="text/javascript" src="js/commands/create.js"></script>
<script type="text/javascript" src="js/commands/textchange.js"></script>
<script type="text/javascript" src="js/commands/rotate.js"></script>
<script type="text/javascript" src="js/commands/delete.js"></script>

<script type="text/javascript" src="js/transport.js"></script>

<script type="text/javascript" src="js/notification.js"></script>

<!-- CSS -->
<link href="css/main.css" rel="stylesheet" type="text/css" />
<link href="css/sidebar.css" rel="stylesheet" type="text/css" />
<link href="css/canvas.css" rel="stylesheet" type="text/css" />
<link href="css/dialog.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="sidebar"></div>
<div id="canvas"></div>


<?php if (config::debug_mode): ?>
<script type="text/javascript" src="js/lib/Stats.js"></script>
<script>
if(!$.browser.msie) {
	var stats = new Stats();

	//Align top-right
	stats.domElement.style.position = "absolute";
	stats.domElement.style.top = "10px";
	stats.domElement.style.right = "10px";

	document.body.appendChild(stats.domElement);

	window.setInterval(function () { stats.update(); }, 1000 / 60);
}
</script>
<?php endif;?>

</body>
</html>