<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Visio Online</title>

<!-- Libraries -->
<script type="text/javascript" src="js/lib/jquery-1.5.min.js"></script>

<script type="text/javascript" src="js/vonline.js"></script>
<script type="text/javascript" src="js/functions.js"></script>
<script type="text/javascript" src="js/list/bootstrap.js"></script>

<script type="text/javascript" src="js/menu.js"></script>
<script type="text/javascript" src="js/menuitem.js"></script>

<script type="text/javascript" src="js/dialog.js"></script>

<script type="text/javascript" src="js/list/documentlist.js"></script>
<script type="text/javascript" src="js/list/documentitem.js"></script>


<!-- CSS -->
<link href="css/main.css" rel="stylesheet" type="text/css" />
<link href="css/sidebar.css" rel="stylesheet" type="text/css" />
<link href="css/documentlist.css" rel="stylesheet" type="text/css" />
<link href="css/dialog.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="topmenu"></div>
<div id="documentlist"></div>
<div class="about"><a id="about">about Visio-Online</a></div>

</body>
</html>