<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Visio Online</title>

<!-- Libraries -->
<script type="text/javascript" src="js/lib/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="js/lib/raphael-min.js"></script>

<!-- JavaScript -->
<script type="text/javascript" src="js/bootstrap.js"></script>

<script type="text/javascript" src="js/document.js"></script>

<script type="text/javascript" src="js/sidebar.js"></script>

<script type="text/javascript" src="js/menu.js"></script>
<script type="text/javascript" src="js/menuitem.js"></script>

<script type="text/javascript" src="js/category.js"></script>

<!-- CSS -->
<link href="css/main.css" rel="stylesheet" type="text/css" />
<link href="css/sidebar.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="sidebar"></div>

</body>
</html>